version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false # Allow _ = for intentionally ignored errors in defer
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
  exclusions:
    generated: lax
    rules:
      # Exclude some linters from running on test files
      - path: _test\.go
        linters:
          - errcheck
