// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: components/linux/action.proto

package linux

import (
	reflect "reflect"
	unsafe "unsafe"

	api "github.com/Azure/AKSFlexNode/components/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigureBaseOS struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata          `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *ConfigureBaseOSSpec   `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *ConfigureBaseOSStatus `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConfigureBaseOS) Reset() {
	*x = ConfigureBaseOS{}
	mi := &file_components_linux_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureBaseOS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureBaseOS) ProtoMessage() {}

func (x *ConfigureBaseOS) ProtoReflect() protoreflect.Message {
	mi := &file_components_linux_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigureBaseOS) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *ConfigureBaseOS) GetSpec() *ConfigureBaseOSSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *ConfigureBaseOS) GetStatus() *ConfigureBaseOSStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *ConfigureBaseOS) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *ConfigureBaseOS) SetSpec(v *ConfigureBaseOSSpec) {
	x.xxx_hidden_Spec = v
}

func (x *ConfigureBaseOS) SetStatus(v *ConfigureBaseOSStatus) {
	x.xxx_hidden_Status = v
}

func (x *ConfigureBaseOS) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *ConfigureBaseOS) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *ConfigureBaseOS) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *ConfigureBaseOS) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *ConfigureBaseOS) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *ConfigureBaseOS) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type ConfigureBaseOS_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *ConfigureBaseOSSpec
	Status   *ConfigureBaseOSStatus
}

func (b0 ConfigureBaseOS_builder) Build() *ConfigureBaseOS {
	m0 := &ConfigureBaseOS{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type ConfigureBaseOSSpec struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureBaseOSSpec) Reset() {
	*x = ConfigureBaseOSSpec{}
	mi := &file_components_linux_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureBaseOSSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureBaseOSSpec) ProtoMessage() {}

func (x *ConfigureBaseOSSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_linux_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ConfigureBaseOSSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ConfigureBaseOSSpec_builder) Build() *ConfigureBaseOSSpec {
	m0 := &ConfigureBaseOSSpec{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ConfigureBaseOSStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureBaseOSStatus) Reset() {
	*x = ConfigureBaseOSStatus{}
	mi := &file_components_linux_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureBaseOSStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureBaseOSStatus) ProtoMessage() {}

func (x *ConfigureBaseOSStatus) ProtoReflect() protoreflect.Message {
	mi := &file_components_linux_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ConfigureBaseOSStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ConfigureBaseOSStatus_builder) Build() *ConfigureBaseOSStatus {
	m0 := &ConfigureBaseOSStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_components_linux_action_proto protoreflect.FileDescriptor

const file_components_linux_action_proto_rawDesc = "" +
	"\n" +
	"\x1dcomponents/linux/action.proto\x12\x19aks.flex.components.linux\x1a\x18components/api/api.proto\"\xde\x01\n" +
	"\x0fConfigureBaseOS\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.aks.flex.components.api.MetadataR\bmetadata\x12B\n" +
	"\x04spec\x18\x02 \x01(\v2..aks.flex.components.linux.ConfigureBaseOSSpecR\x04spec\x12H\n" +
	"\x06status\x18\x03 \x01(\v20.aks.flex.components.linux.ConfigureBaseOSStatusR\x06status\"\x15\n" +
	"\x13ConfigureBaseOSSpec\"\x17\n" +
	"\x15ConfigureBaseOSStatusB-Z+github.com/Azure/AKSFlexNode/components/linuxb\beditionsp\xe9\a"

var file_components_linux_action_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_components_linux_action_proto_goTypes = []any{
	(*ConfigureBaseOS)(nil),       // 0: aks.flex.components.linux.ConfigureBaseOS
	(*ConfigureBaseOSSpec)(nil),   // 1: aks.flex.components.linux.ConfigureBaseOSSpec
	(*ConfigureBaseOSStatus)(nil), // 2: aks.flex.components.linux.ConfigureBaseOSStatus
	(*api.Metadata)(nil),          // 3: aks.flex.components.api.Metadata
}
var file_components_linux_action_proto_depIdxs = []int32{
	3, // 0: aks.flex.components.linux.ConfigureBaseOS.metadata:type_name -> aks.flex.components.api.Metadata
	1, // 1: aks.flex.components.linux.ConfigureBaseOS.spec:type_name -> aks.flex.components.linux.ConfigureBaseOSSpec
	2, // 2: aks.flex.components.linux.ConfigureBaseOS.status:type_name -> aks.flex.components.linux.ConfigureBaseOSStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_components_linux_action_proto_init() }
func file_components_linux_action_proto_init() {
	if File_components_linux_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_linux_action_proto_rawDesc), len(file_components_linux_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_linux_action_proto_goTypes,
		DependencyIndexes: file_components_linux_action_proto_depIdxs,
		MessageInfos:      file_components_linux_action_proto_msgTypes,
	}.Build()
	File_components_linux_action_proto = out.File
	file_components_linux_action_proto_goTypes = nil
	file_components_linux_action_proto_depIdxs = nil
}
