// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: components/aksmachine/action.proto

package aksmachine

import (
	reflect "reflect"
	unsafe "unsafe"

	api "github.com/Azure/AKSFlexNode/components/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AzureServicePrincipalCredential struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId     *string                `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId"`
	xxx_hidden_ClientId     *string                `protobuf:"bytes,2,opt,name=client_id,json=clientId"`
	xxx_hidden_ClientSecret *string                `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AzureServicePrincipalCredential) Reset() {
	*x = AzureServicePrincipalCredential{}
	mi := &file_components_aksmachine_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureServicePrincipalCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureServicePrincipalCredential) ProtoMessage() {}

func (x *AzureServicePrincipalCredential) ProtoReflect() protoreflect.Message {
	mi := &file_components_aksmachine_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AzureServicePrincipalCredential) GetTenantId() string {
	if x != nil {
		if x.xxx_hidden_TenantId != nil {
			return *x.xxx_hidden_TenantId
		}
		return ""
	}
	return ""
}

func (x *AzureServicePrincipalCredential) GetClientId() string {
	if x != nil {
		if x.xxx_hidden_ClientId != nil {
			return *x.xxx_hidden_ClientId
		}
		return ""
	}
	return ""
}

func (x *AzureServicePrincipalCredential) GetClientSecret() string {
	if x != nil {
		if x.xxx_hidden_ClientSecret != nil {
			return *x.xxx_hidden_ClientSecret
		}
		return ""
	}
	return ""
}

func (x *AzureServicePrincipalCredential) SetTenantId(v string) {
	x.xxx_hidden_TenantId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *AzureServicePrincipalCredential) SetClientId(v string) {
	x.xxx_hidden_ClientId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *AzureServicePrincipalCredential) SetClientSecret(v string) {
	x.xxx_hidden_ClientSecret = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *AzureServicePrincipalCredential) HasTenantId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AzureServicePrincipalCredential) HasClientId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AzureServicePrincipalCredential) HasClientSecret() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AzureServicePrincipalCredential) ClearTenantId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TenantId = nil
}

func (x *AzureServicePrincipalCredential) ClearClientId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ClientId = nil
}

func (x *AzureServicePrincipalCredential) ClearClientSecret() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ClientSecret = nil
}

type AzureServicePrincipalCredential_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId     *string
	ClientId     *string
	ClientSecret *string
}

func (b0 AzureServicePrincipalCredential_builder) Build() *AzureServicePrincipalCredential {
	m0 := &AzureServicePrincipalCredential{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TenantId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_TenantId = b.TenantId
	}
	if b.ClientId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_ClientId = b.ClientId
	}
	if b.ClientSecret != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_ClientSecret = b.ClientSecret
	}
	return m0
}

type AzureMSICredential struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ClientId    *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AzureMSICredential) Reset() {
	*x = AzureMSICredential{}
	mi := &file_components_aksmachine_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureMSICredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureMSICredential) ProtoMessage() {}

func (x *AzureMSICredential) ProtoReflect() protoreflect.Message {
	mi := &file_components_aksmachine_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AzureMSICredential) GetClientId() string {
	if x != nil {
		if x.xxx_hidden_ClientId != nil {
			return *x.xxx_hidden_ClientId
		}
		return ""
	}
	return ""
}

func (x *AzureMSICredential) SetClientId(v string) {
	x.xxx_hidden_ClientId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AzureMSICredential) HasClientId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AzureMSICredential) ClearClientId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ClientId = nil
}

type AzureMSICredential_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Client ID of the managed identity; empty means system-assigned MI.
	ClientId *string
}

func (b0 AzureMSICredential_builder) Build() *AzureMSICredential {
	m0 := &AzureMSICredential{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ClientId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ClientId = b.ClientId
	}
	return m0
}

// AzureCredential carries the ARM authentication credential for the action.
// If neither field is set the action falls back to Azure CLI credential.
type AzureCredential struct {
	state                 protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Credential isAzureCredential_Credential `protobuf_oneof:"credential"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AzureCredential) Reset() {
	*x = AzureCredential{}
	mi := &file_components_aksmachine_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureCredential) ProtoMessage() {}

func (x *AzureCredential) ProtoReflect() protoreflect.Message {
	mi := &file_components_aksmachine_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AzureCredential) GetServicePrincipal() *AzureServicePrincipalCredential {
	if x != nil {
		if x, ok := x.xxx_hidden_Credential.(*azureCredential_ServicePrincipal); ok {
			return x.ServicePrincipal
		}
	}
	return nil
}

func (x *AzureCredential) GetManagedIdentity() *AzureMSICredential {
	if x != nil {
		if x, ok := x.xxx_hidden_Credential.(*azureCredential_ManagedIdentity); ok {
			return x.ManagedIdentity
		}
	}
	return nil
}

func (x *AzureCredential) SetServicePrincipal(v *AzureServicePrincipalCredential) {
	if v == nil {
		x.xxx_hidden_Credential = nil
		return
	}
	x.xxx_hidden_Credential = &azureCredential_ServicePrincipal{v}
}

func (x *AzureCredential) SetManagedIdentity(v *AzureMSICredential) {
	if v == nil {
		x.xxx_hidden_Credential = nil
		return
	}
	x.xxx_hidden_Credential = &azureCredential_ManagedIdentity{v}
}

func (x *AzureCredential) HasCredential() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Credential != nil
}

func (x *AzureCredential) HasServicePrincipal() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Credential.(*azureCredential_ServicePrincipal)
	return ok
}

func (x *AzureCredential) HasManagedIdentity() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Credential.(*azureCredential_ManagedIdentity)
	return ok
}

func (x *AzureCredential) ClearCredential() {
	x.xxx_hidden_Credential = nil
}

func (x *AzureCredential) ClearServicePrincipal() {
	if _, ok := x.xxx_hidden_Credential.(*azureCredential_ServicePrincipal); ok {
		x.xxx_hidden_Credential = nil
	}
}

func (x *AzureCredential) ClearManagedIdentity() {
	if _, ok := x.xxx_hidden_Credential.(*azureCredential_ManagedIdentity); ok {
		x.xxx_hidden_Credential = nil
	}
}

const AzureCredential_Credential_not_set_case case_AzureCredential_Credential = 0
const AzureCredential_ServicePrincipal_case case_AzureCredential_Credential = 1
const AzureCredential_ManagedIdentity_case case_AzureCredential_Credential = 2

func (x *AzureCredential) WhichCredential() case_AzureCredential_Credential {
	if x == nil {
		return AzureCredential_Credential_not_set_case
	}
	switch x.xxx_hidden_Credential.(type) {
	case *azureCredential_ServicePrincipal:
		return AzureCredential_ServicePrincipal_case
	case *azureCredential_ManagedIdentity:
		return AzureCredential_ManagedIdentity_case
	default:
		return AzureCredential_Credential_not_set_case
	}
}

type AzureCredential_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Credential:
	ServicePrincipal *AzureServicePrincipalCredential
	ManagedIdentity  *AzureMSICredential
	// -- end of xxx_hidden_Credential
}

func (b0 AzureCredential_builder) Build() *AzureCredential {
	m0 := &AzureCredential{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ServicePrincipal != nil {
		x.xxx_hidden_Credential = &azureCredential_ServicePrincipal{b.ServicePrincipal}
	}
	if b.ManagedIdentity != nil {
		x.xxx_hidden_Credential = &azureCredential_ManagedIdentity{b.ManagedIdentity}
	}
	return m0
}

type case_AzureCredential_Credential protoreflect.FieldNumber

func (x case_AzureCredential_Credential) String() string {
	md := file_components_aksmachine_action_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isAzureCredential_Credential interface {
	isAzureCredential_Credential()
}

type azureCredential_ServicePrincipal struct {
	ServicePrincipal *AzureServicePrincipalCredential `protobuf:"bytes,1,opt,name=service_principal,json=servicePrincipal,oneof"`
}

type azureCredential_ManagedIdentity struct {
	ManagedIdentity *AzureMSICredential `protobuf:"bytes,2,opt,name=managed_identity,json=managedIdentity,oneof"`
}

func (*azureCredential_ServicePrincipal) isAzureCredential_Credential() {}

func (*azureCredential_ManagedIdentity) isAzureCredential_Credential() {}

type EnsureMachine struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata          `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *EnsureMachineSpec     `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *EnsureMachineStatus   `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EnsureMachine) Reset() {
	*x = EnsureMachine{}
	mi := &file_components_aksmachine_action_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureMachine) ProtoMessage() {}

func (x *EnsureMachine) ProtoReflect() protoreflect.Message {
	mi := &file_components_aksmachine_action_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EnsureMachine) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *EnsureMachine) GetSpec() *EnsureMachineSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *EnsureMachine) GetStatus() *EnsureMachineStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *EnsureMachine) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *EnsureMachine) SetSpec(v *EnsureMachineSpec) {
	x.xxx_hidden_Spec = v
}

func (x *EnsureMachine) SetStatus(v *EnsureMachineStatus) {
	x.xxx_hidden_Status = v
}

func (x *EnsureMachine) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *EnsureMachine) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *EnsureMachine) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *EnsureMachine) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *EnsureMachine) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *EnsureMachine) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type EnsureMachine_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *EnsureMachineSpec
	Status   *EnsureMachineStatus
}

func (b0 EnsureMachine_builder) Build() *EnsureMachine {
	m0 := &EnsureMachine{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type EnsureMachineSpec struct {
	state                               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SubscriptionId           *string                `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId"`
	xxx_hidden_ResourceGroup            *string                `protobuf:"bytes,2,opt,name=resource_group,json=resourceGroup"`
	xxx_hidden_ClusterName              *string                `protobuf:"bytes,3,opt,name=cluster_name,json=clusterName"`
	xxx_hidden_MachineName              *string                `protobuf:"bytes,4,opt,name=machine_name,json=machineName"`
	xxx_hidden_KubernetesVersion        *string                `protobuf:"bytes,5,opt,name=kubernetes_version,json=kubernetesVersion"`
	xxx_hidden_MaxPods                  int32                  `protobuf:"varint,6,opt,name=max_pods,json=maxPods"`
	xxx_hidden_NodeLabels               map[string]string      `protobuf:"bytes,7,rep,name=node_labels,json=nodeLabels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_NodeTaints               []string               `protobuf:"bytes,8,rep,name=node_taints,json=nodeTaints"`
	xxx_hidden_NodeInitializationTaints []string               `protobuf:"bytes,9,rep,name=node_initialization_taints,json=nodeInitializationTaints"`
	xxx_hidden_KubeletConfig            *MachineKubeletConfig  `protobuf:"bytes,10,opt,name=kubelet_config,json=kubeletConfig"`
	xxx_hidden_Enabled                  bool                   `protobuf:"varint,11,opt,name=enabled"`
	xxx_hidden_AzureCredential          *AzureCredential       `protobuf:"bytes,12,opt,name=azure_credential,json=azureCredential"`
	XXX_raceDetectHookData              protoimpl.RaceDetectHookData
	XXX_presence                        [1]uint32
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *EnsureMachineSpec) Reset() {
	*x = EnsureMachineSpec{}
	mi := &file_components_aksmachine_action_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureMachineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureMachineSpec) ProtoMessage() {}

func (x *EnsureMachineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_aksmachine_action_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EnsureMachineSpec) GetSubscriptionId() string {
	if x != nil {
		if x.xxx_hidden_SubscriptionId != nil {
			return *x.xxx_hidden_SubscriptionId
		}
		return ""
	}
	return ""
}

func (x *EnsureMachineSpec) GetResourceGroup() string {
	if x != nil {
		if x.xxx_hidden_ResourceGroup != nil {
			return *x.xxx_hidden_ResourceGroup
		}
		return ""
	}
	return ""
}

func (x *EnsureMachineSpec) GetClusterName() string {
	if x != nil {
		if x.xxx_hidden_ClusterName != nil {
			return *x.xxx_hidden_ClusterName
		}
		return ""
	}
	return ""
}

func (x *EnsureMachineSpec) GetMachineName() string {
	if x != nil {
		if x.xxx_hidden_MachineName != nil {
			return *x.xxx_hidden_MachineName
		}
		return ""
	}
	return ""
}

func (x *EnsureMachineSpec) GetKubernetesVersion() string {
	if x != nil {
		if x.xxx_hidden_KubernetesVersion != nil {
			return *x.xxx_hidden_KubernetesVersion
		}
		return ""
	}
	return ""
}

func (x *EnsureMachineSpec) GetMaxPods() int32 {
	if x != nil {
		return x.xxx_hidden_MaxPods
	}
	return 0
}

func (x *EnsureMachineSpec) GetNodeLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_NodeLabels
	}
	return nil
}

func (x *EnsureMachineSpec) GetNodeTaints() []string {
	if x != nil {
		return x.xxx_hidden_NodeTaints
	}
	return nil
}

func (x *EnsureMachineSpec) GetNodeInitializationTaints() []string {
	if x != nil {
		return x.xxx_hidden_NodeInitializationTaints
	}
	return nil
}

func (x *EnsureMachineSpec) GetKubeletConfig() *MachineKubeletConfig {
	if x != nil {
		return x.xxx_hidden_KubeletConfig
	}
	return nil
}

func (x *EnsureMachineSpec) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *EnsureMachineSpec) GetAzureCredential() *AzureCredential {
	if x != nil {
		return x.xxx_hidden_AzureCredential
	}
	return nil
}

func (x *EnsureMachineSpec) SetSubscriptionId(v string) {
	x.xxx_hidden_SubscriptionId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 12)
}

func (x *EnsureMachineSpec) SetResourceGroup(v string) {
	x.xxx_hidden_ResourceGroup = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 12)
}

func (x *EnsureMachineSpec) SetClusterName(v string) {
	x.xxx_hidden_ClusterName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 12)
}

func (x *EnsureMachineSpec) SetMachineName(v string) {
	x.xxx_hidden_MachineName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 12)
}

func (x *EnsureMachineSpec) SetKubernetesVersion(v string) {
	x.xxx_hidden_KubernetesVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 12)
}

func (x *EnsureMachineSpec) SetMaxPods(v int32) {
	x.xxx_hidden_MaxPods = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 12)
}

func (x *EnsureMachineSpec) SetNodeLabels(v map[string]string) {
	x.xxx_hidden_NodeLabels = v
}

func (x *EnsureMachineSpec) SetNodeTaints(v []string) {
	x.xxx_hidden_NodeTaints = v
}

func (x *EnsureMachineSpec) SetNodeInitializationTaints(v []string) {
	x.xxx_hidden_NodeInitializationTaints = v
}

func (x *EnsureMachineSpec) SetKubeletConfig(v *MachineKubeletConfig) {
	x.xxx_hidden_KubeletConfig = v
}

func (x *EnsureMachineSpec) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 12)
}

func (x *EnsureMachineSpec) SetAzureCredential(v *AzureCredential) {
	x.xxx_hidden_AzureCredential = v
}

func (x *EnsureMachineSpec) HasSubscriptionId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EnsureMachineSpec) HasResourceGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EnsureMachineSpec) HasClusterName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *EnsureMachineSpec) HasMachineName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *EnsureMachineSpec) HasKubernetesVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *EnsureMachineSpec) HasMaxPods() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *EnsureMachineSpec) HasKubeletConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_KubeletConfig != nil
}

func (x *EnsureMachineSpec) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *EnsureMachineSpec) HasAzureCredential() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AzureCredential != nil
}

func (x *EnsureMachineSpec) ClearSubscriptionId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_SubscriptionId = nil
}

func (x *EnsureMachineSpec) ClearResourceGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ResourceGroup = nil
}

func (x *EnsureMachineSpec) ClearClusterName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ClusterName = nil
}

func (x *EnsureMachineSpec) ClearMachineName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_MachineName = nil
}

func (x *EnsureMachineSpec) ClearKubernetesVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_KubernetesVersion = nil
}

func (x *EnsureMachineSpec) ClearMaxPods() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_MaxPods = 0
}

func (x *EnsureMachineSpec) ClearKubeletConfig() {
	x.xxx_hidden_KubeletConfig = nil
}

func (x *EnsureMachineSpec) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_Enabled = false
}

func (x *EnsureMachineSpec) ClearAzureCredential() {
	x.xxx_hidden_AzureCredential = nil
}

type EnsureMachineSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Azure subscription ID of the target AKS cluster
	SubscriptionId *string
	// Azure resource group of the target AKS cluster
	ResourceGroup *string
	// Name of the target AKS cluster
	ClusterName *string
	// Name of the machine (hostname of the local machine)
	MachineName *string
	// Kubernetes version to join (e.g. "1.30" or "1.30.6")
	KubernetesVersion *string
	// Maximum number of pods that can run on the node
	MaxPods *int32
	// Node labels
	NodeLabels map[string]string
	// Node taints (reconciled by AKS)
	NodeTaints []string
	// Node initialization taints (not reconciled by AKS, removable via kubectl)
	NodeInitializationTaints []string
	// Kubelet configuration
	KubeletConfig *MachineKubeletConfig
	// enabled controls whether the action performs Azure operations.
	// Set to false when drift detection and remediation is disabled.
	Enabled *bool
	// azure_credential is used to authenticate against the Azure ARM API.
	// If unset the action falls back to Azure CLI credential.
	AzureCredential *AzureCredential
}

func (b0 EnsureMachineSpec_builder) Build() *EnsureMachineSpec {
	m0 := &EnsureMachineSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SubscriptionId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 12)
		x.xxx_hidden_SubscriptionId = b.SubscriptionId
	}
	if b.ResourceGroup != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 12)
		x.xxx_hidden_ResourceGroup = b.ResourceGroup
	}
	if b.ClusterName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 12)
		x.xxx_hidden_ClusterName = b.ClusterName
	}
	if b.MachineName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 12)
		x.xxx_hidden_MachineName = b.MachineName
	}
	if b.KubernetesVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 12)
		x.xxx_hidden_KubernetesVersion = b.KubernetesVersion
	}
	if b.MaxPods != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 12)
		x.xxx_hidden_MaxPods = *b.MaxPods
	}
	x.xxx_hidden_NodeLabels = b.NodeLabels
	x.xxx_hidden_NodeTaints = b.NodeTaints
	x.xxx_hidden_NodeInitializationTaints = b.NodeInitializationTaints
	x.xxx_hidden_KubeletConfig = b.KubeletConfig
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 12)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	x.xxx_hidden_AzureCredential = b.AzureCredential
	return m0
}

// MachineKubeletConfig holds the subset of kubelet settings sent to AKS on
// the PUT machine request.
type MachineKubeletConfig struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ImageGcHighThreshold int32                  `protobuf:"varint,1,opt,name=image_gc_high_threshold,json=imageGcHighThreshold"`
	xxx_hidden_ImageGcLowThreshold  int32                  `protobuf:"varint,2,opt,name=image_gc_low_threshold,json=imageGcLowThreshold"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *MachineKubeletConfig) Reset() {
	*x = MachineKubeletConfig{}
	mi := &file_components_aksmachine_action_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineKubeletConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineKubeletConfig) ProtoMessage() {}

func (x *MachineKubeletConfig) ProtoReflect() protoreflect.Message {
	mi := &file_components_aksmachine_action_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MachineKubeletConfig) GetImageGcHighThreshold() int32 {
	if x != nil {
		return x.xxx_hidden_ImageGcHighThreshold
	}
	return 0
}

func (x *MachineKubeletConfig) GetImageGcLowThreshold() int32 {
	if x != nil {
		return x.xxx_hidden_ImageGcLowThreshold
	}
	return 0
}

func (x *MachineKubeletConfig) SetImageGcHighThreshold(v int32) {
	x.xxx_hidden_ImageGcHighThreshold = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *MachineKubeletConfig) SetImageGcLowThreshold(v int32) {
	x.xxx_hidden_ImageGcLowThreshold = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *MachineKubeletConfig) HasImageGcHighThreshold() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MachineKubeletConfig) HasImageGcLowThreshold() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MachineKubeletConfig) ClearImageGcHighThreshold() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ImageGcHighThreshold = 0
}

func (x *MachineKubeletConfig) ClearImageGcLowThreshold() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ImageGcLowThreshold = 0
}

type MachineKubeletConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Percent of disk usage above which image GC always runs (default 85)
	ImageGcHighThreshold *int32
	// Percent of disk usage below which image GC never runs (default 80)
	ImageGcLowThreshold *int32
}

func (b0 MachineKubeletConfig_builder) Build() *MachineKubeletConfig {
	m0 := &MachineKubeletConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ImageGcHighThreshold != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_ImageGcHighThreshold = *b.ImageGcHighThreshold
	}
	if b.ImageGcLowThreshold != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ImageGcLowThreshold = *b.ImageGcLowThreshold
	}
	return m0
}

type EnsureMachineStatus struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureMachineStatus) Reset() {
	*x = EnsureMachineStatus{}
	mi := &file_components_aksmachine_action_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureMachineStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureMachineStatus) ProtoMessage() {}

func (x *EnsureMachineStatus) ProtoReflect() protoreflect.Message {
	mi := &file_components_aksmachine_action_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type EnsureMachineStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 EnsureMachineStatus_builder) Build() *EnsureMachineStatus {
	m0 := &EnsureMachineStatus{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_components_aksmachine_action_proto protoreflect.FileDescriptor

const file_components_aksmachine_action_proto_rawDesc = "" +
	"\n" +
	"\"components/aksmachine/action.proto\x12\x1eaks.flex.components.aksmachine\x1a\x18components/api/api.proto\"\x80\x01\n" +
	"\x1fAzureServicePrincipalCredential\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\"1\n" +
	"\x12AzureMSICredential\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xf0\x01\n" +
	"\x0fAzureCredential\x12n\n" +
	"\x11service_principal\x18\x01 \x01(\v2?.aks.flex.components.aksmachine.AzureServicePrincipalCredentialH\x00R\x10servicePrincipal\x12_\n" +
	"\x10managed_identity\x18\x02 \x01(\v22.aks.flex.components.aksmachine.AzureMSICredentialH\x00R\x0fmanagedIdentityB\f\n" +
	"\n" +
	"credential\"\xe2\x01\n" +
	"\rEnsureMachine\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.aks.flex.components.api.MetadataR\bmetadata\x12E\n" +
	"\x04spec\x18\x02 \x01(\v21.aks.flex.components.aksmachine.EnsureMachineSpecR\x04spec\x12K\n" +
	"\x06status\x18\x03 \x01(\v23.aks.flex.components.aksmachine.EnsureMachineStatusR\x06status\"\xc8\x05\n" +
	"\x11EnsureMachineSpec\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12%\n" +
	"\x0eresource_group\x18\x02 \x01(\tR\rresourceGroup\x12!\n" +
	"\fcluster_name\x18\x03 \x01(\tR\vclusterName\x12!\n" +
	"\fmachine_name\x18\x04 \x01(\tR\vmachineName\x12-\n" +
	"\x12kubernetes_version\x18\x05 \x01(\tR\x11kubernetesVersion\x12\x19\n" +
	"\bmax_pods\x18\x06 \x01(\x05R\amaxPods\x12b\n" +
	"\vnode_labels\x18\a \x03(\v2A.aks.flex.components.aksmachine.EnsureMachineSpec.NodeLabelsEntryR\n" +
	"nodeLabels\x12\x1f\n" +
	"\vnode_taints\x18\b \x03(\tR\n" +
	"nodeTaints\x12<\n" +
	"\x1anode_initialization_taints\x18\t \x03(\tR\x18nodeInitializationTaints\x12[\n" +
	"\x0ekubelet_config\x18\n" +
	" \x01(\v24.aks.flex.components.aksmachine.MachineKubeletConfigR\rkubeletConfig\x12\x18\n" +
	"\aenabled\x18\v \x01(\bR\aenabled\x12Z\n" +
	"\x10azure_credential\x18\f \x01(\v2/.aks.flex.components.aksmachine.AzureCredentialR\x0fazureCredential\x1a=\n" +
	"\x0fNodeLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\x14MachineKubeletConfig\x125\n" +
	"\x17image_gc_high_threshold\x18\x01 \x01(\x05R\x14imageGcHighThreshold\x123\n" +
	"\x16image_gc_low_threshold\x18\x02 \x01(\x05R\x13imageGcLowThreshold\"\x15\n" +
	"\x13EnsureMachineStatusB4Z2github.com/Azure/AKSFlexNode/components/aksmachineb\beditionsp\xe9\a"

var file_components_aksmachine_action_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_components_aksmachine_action_proto_goTypes = []any{
	(*AzureServicePrincipalCredential)(nil), // 0: aks.flex.components.aksmachine.AzureServicePrincipalCredential
	(*AzureMSICredential)(nil),              // 1: aks.flex.components.aksmachine.AzureMSICredential
	(*AzureCredential)(nil),                 // 2: aks.flex.components.aksmachine.AzureCredential
	(*EnsureMachine)(nil),                   // 3: aks.flex.components.aksmachine.EnsureMachine
	(*EnsureMachineSpec)(nil),               // 4: aks.flex.components.aksmachine.EnsureMachineSpec
	(*MachineKubeletConfig)(nil),            // 5: aks.flex.components.aksmachine.MachineKubeletConfig
	(*EnsureMachineStatus)(nil),             // 6: aks.flex.components.aksmachine.EnsureMachineStatus
	nil,                                     // 7: aks.flex.components.aksmachine.EnsureMachineSpec.NodeLabelsEntry
	(*api.Metadata)(nil),                    // 8: aks.flex.components.api.Metadata
}
var file_components_aksmachine_action_proto_depIdxs = []int32{
	0, // 0: aks.flex.components.aksmachine.AzureCredential.service_principal:type_name -> aks.flex.components.aksmachine.AzureServicePrincipalCredential
	1, // 1: aks.flex.components.aksmachine.AzureCredential.managed_identity:type_name -> aks.flex.components.aksmachine.AzureMSICredential
	8, // 2: aks.flex.components.aksmachine.EnsureMachine.metadata:type_name -> aks.flex.components.api.Metadata
	4, // 3: aks.flex.components.aksmachine.EnsureMachine.spec:type_name -> aks.flex.components.aksmachine.EnsureMachineSpec
	6, // 4: aks.flex.components.aksmachine.EnsureMachine.status:type_name -> aks.flex.components.aksmachine.EnsureMachineStatus
	7, // 5: aks.flex.components.aksmachine.EnsureMachineSpec.node_labels:type_name -> aks.flex.components.aksmachine.EnsureMachineSpec.NodeLabelsEntry
	5, // 6: aks.flex.components.aksmachine.EnsureMachineSpec.kubelet_config:type_name -> aks.flex.components.aksmachine.MachineKubeletConfig
	2, // 7: aks.flex.components.aksmachine.EnsureMachineSpec.azure_credential:type_name -> aks.flex.components.aksmachine.AzureCredential
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_components_aksmachine_action_proto_init() }
func file_components_aksmachine_action_proto_init() {
	if File_components_aksmachine_action_proto != nil {
		return
	}
	file_components_aksmachine_action_proto_msgTypes[2].OneofWrappers = []any{
		(*azureCredential_ServicePrincipal)(nil),
		(*azureCredential_ManagedIdentity)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_aksmachine_action_proto_rawDesc), len(file_components_aksmachine_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_aksmachine_action_proto_goTypes,
		DependencyIndexes: file_components_aksmachine_action_proto_depIdxs,
		MessageInfos:      file_components_aksmachine_action_proto_msgTypes,
	}.Build()
	File_components_aksmachine_action_proto = out.File
	file_components_aksmachine_action_proto_goTypes = nil
	file_components_aksmachine_action_proto_depIdxs = nil
}
