imports = ["/etc/containerd/conf.d/*.toml"]

oom_score = 0
version = 3

[plugins.'io.containerd.cri.v1.runtime']
sandbox_image = "{{.SandboxImage}}"

[plugins.'io.containerd.cri.v1.runtime'.containerd]
default_runtime_name = "runc"

[plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.runc]
runtime_type = "io.containerd.runc.v2"

[plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.runc.options]
BinaryName = "{{.RuncBinaryPath}}"
SystemdCgroup = true

[plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.untrusted]
runtime_type = "io.containerd.runc.v2"

[plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.untrusted.options]
BinaryName = "{{.RuncBinaryPath}}"

[plugins.'io.containerd.cri.v1.runtime'.cni]
bin_dir = "{{.CNIBinDir}}"
conf_dir = "{{.CNIConfDir}}"

[plugins.'io.containerd.cri.v1.images']

[plugins.'io.containerd.cri.v1.images'.registry]
config_path = "/etc/containerd/certs.d"

[plugins.'io.containerd.cri.v1.images'.registry.headers]
X-Meta-Source-Client = ["azure/aks"]

[metrics]
address = "{{.MetricsAddress}}"
