package v20260301

import (
	"context"
	_ "embed"
	"fmt"
	"net/netip"
	"strings"

	"google.golang.org/protobuf/types/known/anypb"

	"github.com/Azure/AKSFlexNode/components/linux"
	"github.com/Azure/AKSFlexNode/components/services/actions"
	"github.com/Azure/AKSFlexNode/pkg/config"
	"github.com/Azure/AKSFlexNode/pkg/systemd"
	"github.com/Azure/AKSFlexNode/pkg/utils/utilpb"
)

const (
	checkRouteOverlapUnit       = "check-route-overlap.service"
	checkRouteOverlapScriptPath = config.ConfigDir + "/check-route-overlap.sh"
)

//go:embed assets/check-route-overlap.service
var checkRouteOverlapServiceUnit []byte

// checkRouteOverlapAction installs a oneshot systemd unit that, before
// kubelet starts, verifies that a list of expected IPv4 CIDRs all route
// via the IPv4 default route's outbound interface. The classic failure
// it catches is the Azure ND-isr H200 IB driver shadowing a customer
// VNet CIDR with a connected /16 on ib0 — in that case `ip -4 route get
// <pod-cidr-address>` returns ib0 instead of eth0, traffic blackholes,
// and kubelet looks healthy while pods can't reach the API server.
//
// Pair with ConfigureStaticRoutes (which fixes the overlap) for full
// coverage: the static-routes oneshot is ordered Before this one, so by
// the time the check runs the kernel route table reflects any
// mitigations.
type checkRouteOverlapAction struct {
	systemd systemd.Manager
}

func newCheckRouteOverlapAction() (actions.Server, error) {
	return &checkRouteOverlapAction{
		systemd: systemd.New(),
	}, nil
}

var _ actions.Server = (*checkRouteOverlapAction)(nil)

func (a *checkRouteOverlapAction) ApplyAction(
	ctx context.Context,
	req *actions.ApplyActionRequest,
) (*actions.ApplyActionResponse, error) {
	settings, err := utilpb.AnyTo[*linux.CheckRouteOverlap](req.GetItem())
	if err != nil {
		return nil, err
	}

	spec := settings.GetSpec()
	if err := validateCheckRouteOverlapSpec(spec); err != nil {
		return nil, fmt.Errorf("validating CheckRouteOverlap spec: %w", err)
	}
	mode := spec.GetMode()
	if mode == linux.CheckRouteOverlapSpec_MODE_UNSPECIFIED {
		mode = linux.CheckRouteOverlapSpec_WARN
	}

	script, err := renderCheckRouteOverlapScript(spec.GetExpectedCidrs(), mode)
	if err != nil {
		return nil, fmt.Errorf("rendering check-route-overlap script: %w", err)
	}

	scriptUpdated, err := writeScriptIfChanged(checkRouteOverlapScriptPath, []byte(script))
	if err != nil {
		return nil, fmt.Errorf("writing check-route-overlap script: %w", err)
	}

	if err := a.ensureCheckRouteOverlapUnit(ctx, scriptUpdated); err != nil {
		return nil, fmt.Errorf("configuring check-route-overlap service: %w", err)
	}

	item, err := anypb.New(settings)
	if err != nil {
		return nil, err
	}
	return actions.ApplyActionResponse_builder{Item: item}.Build(), nil
}

func validateCheckRouteOverlapSpec(spec *linux.CheckRouteOverlapSpec) error {
	if spec == nil {
		return fmt.Errorf("spec is required")
	}
	return nil
}

func (a *checkRouteOverlapAction) ensureCheckRouteOverlapUnit(ctx context.Context, scriptUpdated bool) error {
	unitUpdated, err := a.systemd.EnsureUnitFile(ctx, checkRouteOverlapUnit, checkRouteOverlapServiceUnit)
	if err != nil {
		return err
	}
	if err := a.systemd.EnableUnit(ctx, checkRouteOverlapUnit); err != nil {
		return err
	}
	changed := unitUpdated || scriptUpdated
	return systemd.EnsureUnitRunning(ctx, a.systemd, checkRouteOverlapUnit, unitUpdated, changed)
}

// renderCheckRouteOverlapScript produces a bash script that, for each
// expected CIDR, picks a probe address inside the prefix and runs
// `ip -4 route get <probe>` to ask the kernel which interface that
// address would actually go out. Any mismatch with the IPv4 default
// route's interface is logged; in STRICT mode the script then exits 1
// and (because the unit is RequiredBy=kubelet.service) kubelet does
// not start.
func renderCheckRouteOverlapScript(cidrs []string, mode linux.CheckRouteOverlapSpec_Mode) (string, error) {
	type entry struct {
		cidr  string
		probe string
	}
	entries := make([]entry, 0, len(cidrs))
	for i, c := range cidrs {
		prefix, err := netip.ParsePrefix(c)
		if err != nil {
			return "", fmt.Errorf("expected_cidrs[%d]: invalid CIDR %q: %w", i, c, err)
		}
		if !prefix.Addr().Is4() {
			return "", fmt.Errorf("expected_cidrs[%d]: %q is not IPv4", i, c)
		}
		// Probe with first usable address (network address + 1). Works for
		// any prefix shorter than /32; for /32 we just probe the address.
		probe := prefix.Addr()
		if prefix.Bits() < 32 {
			probe = probe.Next()
		}
		entries = append(entries, entry{cidr: c, probe: probe.String()})
	}

	failExit := "0"
	modeLabel := "WARN"
	if mode == linux.CheckRouteOverlapSpec_STRICT {
		failExit = "1"
		modeLabel = "STRICT"
	}

	var b strings.Builder
	fmt.Fprintf(&b, "#!/bin/bash\n")
	fmt.Fprintf(&b, "# Generated by AKSFlexNode CheckRouteOverlap. Do not edit. mode=%s\n", modeLabel)
	b.WriteString("set -eu\n")
	b.WriteString("PATH=/usr/sbin:/sbin:/usr/bin:/bin:${PATH:-}\n\n")
	b.WriteString("mkdir -p /run/aks-flex-node\n")
	b.WriteString("rm -f /run/aks-flex-node/route-overlap.detected\n")
	b.WriteString("rm -f /run/aks-flex-node/route-overlap.ok\n\n")

	b.WriteString("DEFAULT_DEV=$(ip -4 route show default 2>/dev/null | awk '/^default via/ {for (i=1;i<=NF;i++) if ($i==\"dev\") {print $(i+1); exit}}')\n")
	b.WriteString("if [ -z \"$DEFAULT_DEV\" ]; then\n")
	b.WriteString("  echo \"check-route-overlap: no IPv4 default route; cannot determine outbound interface\" >&2\n")
	b.WriteString("  echo \"no-default-route\" > /run/aks-flex-node/route-overlap.detected\n")
	fmt.Fprintf(&b, "  exit %s\n", failExit)
	b.WriteString("fi\n\n")

	if len(entries) == 0 {
		b.WriteString("echo \"check-route-overlap: no expected CIDRs configured; nothing to check (default dev: $DEFAULT_DEV)\"\n")
		b.WriteString("touch /run/aks-flex-node/route-overlap.ok\n")
		b.WriteString("exit 0\n")
		return b.String(), nil
	}

	b.WriteString("bad=0\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "# expected: %s (probe %s)\n", e.cidr, e.probe)
		fmt.Fprintf(&b, "ACTUAL=$(ip -4 route get %s 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i==\"dev\") {print $(i+1); exit}}')\n", e.probe)
		b.WriteString("if [ -z \"$ACTUAL\" ]; then ACTUAL=\"<no-route>\"; fi\n")
		b.WriteString("if [ \"$ACTUAL\" != \"$DEFAULT_DEV\" ]; then\n")
		fmt.Fprintf(&b, "  msg=\"OVERLAP: expected CIDR %s (probe %s) routes via $ACTUAL, expected $DEFAULT_DEV\"\n", e.cidr, e.probe)
		b.WriteString("  echo \"$msg\" >&2\n")
		b.WriteString("  echo \"$msg\" >> /run/aks-flex-node/route-overlap.detected\n")
		b.WriteString("  bad=1\n")
		b.WriteString("fi\n\n")
	}

	b.WriteString("if [ \"$bad\" -eq 1 ]; then\n")
	b.WriteString("  cat >&2 <<'EOF'\n")
	b.WriteString("Action: configure spec.staticRoutes on the NodeClass with more-specific\n")
	b.WriteString("routes for the affected CIDRs, or rebuild the cluster on a non-overlapping\n")
	b.WriteString("VNet CIDR. See AKSFlexNode/components/linux/v20260301/configure_static_routes.go.\n")
	b.WriteString("EOF\n")
	fmt.Fprintf(&b, "  exit %s\n", failExit)
	b.WriteString("fi\n\n")
	b.WriteString("echo \"check-route-overlap: all expected CIDRs route via $DEFAULT_DEV\"\n")
	b.WriteString("touch /run/aks-flex-node/route-overlap.ok\n")
	b.WriteString("exit 0\n")

	return b.String(), nil
}
