package v20260301

import (
	"context"
	_ "embed"
	"fmt"
	"net/netip"
	"strings"

	"google.golang.org/protobuf/types/known/anypb"

	"github.com/Azure/AKSFlexNode/components/linux"
	"github.com/Azure/AKSFlexNode/components/services/actions"
	"github.com/Azure/AKSFlexNode/pkg/config"
	"github.com/Azure/AKSFlexNode/pkg/systemd"
	"github.com/Azure/AKSFlexNode/pkg/utils/utilio"
	"github.com/Azure/AKSFlexNode/pkg/utils/utilpb"
)

const (
	staticRoutesUnit       = "static-routes.service"
	staticRoutesScriptPath = config.ConfigDir + "/static-routes.sh"
)

//go:embed assets/static-routes.service
var staticRoutesServiceUnit []byte

// configureStaticRoutesAction installs a oneshot systemd unit that applies
// one or more static IPv4 routes via `ip route replace` before kubelet
// starts. Intended for cases where the VM provider's default routing is
// wrong for the cluster — for example, Azure ND-isr SKUs install connected
// /16 routes for the InfiniBand fabric that can shadow legitimate cluster
// CIDRs. More-specific routes added via this action win over the IB /16
// without disturbing peer-to-peer IB traffic.
type configureStaticRoutesAction struct {
	systemd systemd.Manager
}

func newConfigureStaticRoutesAction() (actions.Server, error) {
	return &configureStaticRoutesAction{
		systemd: systemd.New(),
	}, nil
}

var _ actions.Server = (*configureStaticRoutesAction)(nil)

func (a *configureStaticRoutesAction) ApplyAction(
	ctx context.Context,
	req *actions.ApplyActionRequest,
) (*actions.ApplyActionResponse, error) {
	settings, err := utilpb.AnyTo[*linux.ConfigureStaticRoutes](req.GetItem())
	if err != nil {
		return nil, err
	}

	routes := settings.GetSpec().GetRoutes()
	script, err := renderStaticRoutesScript(routes)
	if err != nil {
		return nil, fmt.Errorf("rendering static-routes script: %w", err)
	}

	if err := utilio.WriteFile(staticRoutesScriptPath, []byte(script), 0o755); err != nil {
		return nil, fmt.Errorf("writing static-routes script: %w", err)
	}

	if err := a.ensureStaticRoutesUnit(ctx); err != nil {
		return nil, fmt.Errorf("configuring static-routes service: %w", err)
	}

	item, err := anypb.New(settings)
	if err != nil {
		return nil, err
	}
	return actions.ApplyActionResponse_builder{Item: item}.Build(), nil
}

// ensureStaticRoutesUnit installs, enables, and (re)starts the
// static-routes.service oneshot unit. The unit runs the script at
// /etc/aks-flex-node/static-routes.sh before kubelet.service starts.
func (a *configureStaticRoutesAction) ensureStaticRoutesUnit(ctx context.Context) error {
	unitUpdated, err := a.systemd.EnsureUnitFile(ctx, staticRoutesUnit, staticRoutesServiceUnit)
	if err != nil {
		return err
	}
	if err := a.systemd.EnableUnit(ctx, staticRoutesUnit); err != nil {
		return err
	}
	// The script content may have changed even when the unit file didn't,
	// so we pass unitUpdated for both update flags to trigger a restart
	// whenever anything in the pipeline has changed. The oneshot is cheap.
	return systemd.EnsureUnitRunning(ctx, a.systemd, staticRoutesUnit, unitUpdated, unitUpdated)
}

// renderStaticRoutesScript produces an idempotent bash script that applies
// each route via `ip route replace`. Routes without an explicit gateway
// resolve to the default gateway on `dev` (or eth0 if `dev` is empty) at
// script runtime.
func renderStaticRoutesScript(routes []*linux.StaticRoute) (string, error) {
	var b strings.Builder
	b.WriteString("#!/bin/bash\n")
	b.WriteString("# Generated by AKSFlexNode ConfigureStaticRoutes. Do not edit.\n")
	b.WriteString("set -eu\n")
	b.WriteString("PATH=/usr/sbin:/sbin:/usr/bin:/bin:${PATH:-}\n\n")
	b.WriteString(`# resolve_default_gw <dev>: prints the default gateway for <dev>, empty if none.` + "\n")
	b.WriteString("resolve_default_gw() {\n")
	b.WriteString("  local dev=\"$1\"\n")
	b.WriteString("  ip -4 route show default dev \"$dev\" 2>/dev/null | awk '/^default via/ {print $3; exit}'\n")
	b.WriteString("}\n\n")

	if len(routes) == 0 {
		b.WriteString("# No routes configured; nothing to do.\n")
		b.WriteString("exit 0\n")
		return b.String(), nil
	}

	for i, r := range routes {
		dest := r.GetDestination()
		if _, err := netip.ParsePrefix(dest); err != nil {
			return "", fmt.Errorf("route %d: invalid destination %q: %w", i, dest, err)
		}
		if gw := r.GetGateway(); gw != "" {
			if _, err := netip.ParseAddr(gw); err != nil {
				return "", fmt.Errorf("route %d: invalid gateway %q: %w", i, gw, err)
			}
		}
		if dev := r.GetDev(); dev != "" && !isSafeIfaceName(dev) {
			return "", fmt.Errorf("route %d: invalid dev name %q", i, dev)
		}

		dev := r.GetDev()
		if dev == "" {
			dev = "eth0"
		}
		gw := r.GetGateway()

		fmt.Fprintf(&b, "# route %d: %s\n", i, dest)
		if gw == "" {
			fmt.Fprintf(&b, "GW=$(resolve_default_gw %q)\n", dev)
			b.WriteString("if [ -z \"$GW\" ]; then\n")
			fmt.Fprintf(&b, "  echo \"no default gateway on %s; skipping %s\" >&2\n", dev, dest)
			b.WriteString("else\n")
			cmd := fmt.Sprintf("ip route replace %s via \"$GW\" dev %q", dest, dev)
			if r.GetMetric() > 0 {
				cmd += fmt.Sprintf(" metric %d", r.GetMetric())
			}
			fmt.Fprintf(&b, "  %s\n", cmd)
			b.WriteString("fi\n\n")
		} else {
			fmt.Fprintf(&b, "GW=%q\n", gw)
			cmd := fmt.Sprintf("ip route replace %s via \"$GW\" dev %q", dest, dev)
			if r.GetMetric() > 0 {
				cmd += fmt.Sprintf(" metric %d", r.GetMetric())
			}
			fmt.Fprintf(&b, "%s\n\n", cmd)
		}
	}
	b.WriteString("exit 0\n")
	return b.String(), nil
}

// isSafeIfaceName rejects shell metacharacters to keep the generated script
// safe against malformed spec inputs. Linux interface names are <=15 chars
// of [A-Za-z0-9_.-].
func isSafeIfaceName(s string) bool {
	if len(s) == 0 || len(s) > 15 {
		return false
	}
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z':
		case r >= 'A' && r <= 'Z':
		case r >= '0' && r <= '9':
		case r == '_' || r == '.' || r == '-':
		default:
			return false
		}
	}
	return true
}
