// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: components/cri/v20260301/action.proto

package v20260301

import (
	api "go.goms.io/aks/AKSFlexNode/components/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadCRIBinaries struct {
	state               protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Metadata *api.Metadata              `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Spec     *DownloadCRIBinariesSpec   `protobuf:"bytes,2,opt,name=spec"`
	xxx_hidden_Status   *DownloadCRIBinariesStatus `protobuf:"bytes,3,opt,name=status"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DownloadCRIBinaries) Reset() {
	*x = DownloadCRIBinaries{}
	mi := &file_components_cri_v20260301_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadCRIBinaries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadCRIBinaries) ProtoMessage() {}

func (x *DownloadCRIBinaries) ProtoReflect() protoreflect.Message {
	mi := &file_components_cri_v20260301_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadCRIBinaries) GetMetadata() *api.Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *DownloadCRIBinaries) GetSpec() *DownloadCRIBinariesSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *DownloadCRIBinaries) GetStatus() *DownloadCRIBinariesStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *DownloadCRIBinaries) SetMetadata(v *api.Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *DownloadCRIBinaries) SetSpec(v *DownloadCRIBinariesSpec) {
	x.xxx_hidden_Spec = v
}

func (x *DownloadCRIBinaries) SetStatus(v *DownloadCRIBinariesStatus) {
	x.xxx_hidden_Status = v
}

func (x *DownloadCRIBinaries) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *DownloadCRIBinaries) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *DownloadCRIBinaries) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *DownloadCRIBinaries) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *DownloadCRIBinaries) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *DownloadCRIBinaries) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type DownloadCRIBinaries_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Metadata *api.Metadata
	Spec     *DownloadCRIBinariesSpec
	Status   *DownloadCRIBinariesStatus
}

func (b0 DownloadCRIBinaries_builder) Build() *DownloadCRIBinaries {
	m0 := &DownloadCRIBinaries{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type DownloadCRIBinariesSpec struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerdVersion *string                `protobuf:"bytes,1,opt,name=containerd_version,json=containerdVersion"`
	xxx_hidden_RuncVersion       *string                `protobuf:"bytes,2,opt,name=runc_version,json=runcVersion"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *DownloadCRIBinariesSpec) Reset() {
	*x = DownloadCRIBinariesSpec{}
	mi := &file_components_cri_v20260301_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadCRIBinariesSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadCRIBinariesSpec) ProtoMessage() {}

func (x *DownloadCRIBinariesSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_cri_v20260301_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadCRIBinariesSpec) GetContainerdVersion() string {
	if x != nil {
		if x.xxx_hidden_ContainerdVersion != nil {
			return *x.xxx_hidden_ContainerdVersion
		}
		return ""
	}
	return ""
}

func (x *DownloadCRIBinariesSpec) GetRuncVersion() string {
	if x != nil {
		if x.xxx_hidden_RuncVersion != nil {
			return *x.xxx_hidden_RuncVersion
		}
		return ""
	}
	return ""
}

func (x *DownloadCRIBinariesSpec) SetContainerdVersion(v string) {
	x.xxx_hidden_ContainerdVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *DownloadCRIBinariesSpec) SetRuncVersion(v string) {
	x.xxx_hidden_RuncVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DownloadCRIBinariesSpec) HasContainerdVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DownloadCRIBinariesSpec) HasRuncVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DownloadCRIBinariesSpec) ClearContainerdVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContainerdVersion = nil
}

func (x *DownloadCRIBinariesSpec) ClearRuncVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_RuncVersion = nil
}

type DownloadCRIBinariesSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerdVersion *string
	RuncVersion       *string
}

func (b0 DownloadCRIBinariesSpec_builder) Build() *DownloadCRIBinariesSpec {
	m0 := &DownloadCRIBinariesSpec{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContainerdVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_ContainerdVersion = b.ContainerdVersion
	}
	if b.RuncVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_RuncVersion = b.RuncVersion
	}
	return m0
}

type DownloadCRIBinariesStatus struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerdDownloadUrl *string                `protobuf:"bytes,1,opt,name=containerd_download_url,json=containerdDownloadUrl"`
	xxx_hidden_ContainerdPath        *string                `protobuf:"bytes,2,opt,name=containerd_path,json=containerdPath"`
	xxx_hidden_RuncDownloadUrl       *string                `protobuf:"bytes,3,opt,name=runc_download_url,json=runcDownloadUrl"`
	xxx_hidden_RuncPath              *string                `protobuf:"bytes,4,opt,name=runc_path,json=runcPath"`
	XXX_raceDetectHookData           protoimpl.RaceDetectHookData
	XXX_presence                     [1]uint32
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *DownloadCRIBinariesStatus) Reset() {
	*x = DownloadCRIBinariesStatus{}
	mi := &file_components_cri_v20260301_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadCRIBinariesStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadCRIBinariesStatus) ProtoMessage() {}

func (x *DownloadCRIBinariesStatus) ProtoReflect() protoreflect.Message {
	mi := &file_components_cri_v20260301_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadCRIBinariesStatus) GetContainerdDownloadUrl() string {
	if x != nil {
		if x.xxx_hidden_ContainerdDownloadUrl != nil {
			return *x.xxx_hidden_ContainerdDownloadUrl
		}
		return ""
	}
	return ""
}

func (x *DownloadCRIBinariesStatus) GetContainerdPath() string {
	if x != nil {
		if x.xxx_hidden_ContainerdPath != nil {
			return *x.xxx_hidden_ContainerdPath
		}
		return ""
	}
	return ""
}

func (x *DownloadCRIBinariesStatus) GetRuncDownloadUrl() string {
	if x != nil {
		if x.xxx_hidden_RuncDownloadUrl != nil {
			return *x.xxx_hidden_RuncDownloadUrl
		}
		return ""
	}
	return ""
}

func (x *DownloadCRIBinariesStatus) GetRuncPath() string {
	if x != nil {
		if x.xxx_hidden_RuncPath != nil {
			return *x.xxx_hidden_RuncPath
		}
		return ""
	}
	return ""
}

func (x *DownloadCRIBinariesStatus) SetContainerdDownloadUrl(v string) {
	x.xxx_hidden_ContainerdDownloadUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *DownloadCRIBinariesStatus) SetContainerdPath(v string) {
	x.xxx_hidden_ContainerdPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *DownloadCRIBinariesStatus) SetRuncDownloadUrl(v string) {
	x.xxx_hidden_RuncDownloadUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *DownloadCRIBinariesStatus) SetRuncPath(v string) {
	x.xxx_hidden_RuncPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *DownloadCRIBinariesStatus) HasContainerdDownloadUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DownloadCRIBinariesStatus) HasContainerdPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DownloadCRIBinariesStatus) HasRuncDownloadUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DownloadCRIBinariesStatus) HasRuncPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DownloadCRIBinariesStatus) ClearContainerdDownloadUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContainerdDownloadUrl = nil
}

func (x *DownloadCRIBinariesStatus) ClearContainerdPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ContainerdPath = nil
}

func (x *DownloadCRIBinariesStatus) ClearRuncDownloadUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_RuncDownloadUrl = nil
}

func (x *DownloadCRIBinariesStatus) ClearRuncPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_RuncPath = nil
}

type DownloadCRIBinariesStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerdDownloadUrl *string
	ContainerdPath        *string
	RuncDownloadUrl       *string
	RuncPath              *string
}

func (b0 DownloadCRIBinariesStatus_builder) Build() *DownloadCRIBinariesStatus {
	m0 := &DownloadCRIBinariesStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContainerdDownloadUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_ContainerdDownloadUrl = b.ContainerdDownloadUrl
	}
	if b.ContainerdPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_ContainerdPath = b.ContainerdPath
	}
	if b.RuncDownloadUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_RuncDownloadUrl = b.RuncDownloadUrl
	}
	if b.RuncPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_RuncPath = b.RuncPath
	}
	return m0
}

var File_components_cri_v20260301_action_proto protoreflect.FileDescriptor

const file_components_cri_v20260301_action_proto_rawDesc = "" +
	"\n" +
	"%components/cri/v20260301/action.proto\x12!aks.flex.components.cri.v20260301\x1a\x18components/api/api.proto\"\xfa\x01\n" +
	"\x13DownloadCRIBinaries\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.aks.flex.components.api.MetadataR\bmetadata\x12N\n" +
	"\x04spec\x18\x02 \x01(\v2:.aks.flex.components.cri.v20260301.DownloadCRIBinariesSpecR\x04spec\x12T\n" +
	"\x06status\x18\x03 \x01(\v2<.aks.flex.components.cri.v20260301.DownloadCRIBinariesStatusR\x06status\"k\n" +
	"\x17DownloadCRIBinariesSpec\x12-\n" +
	"\x12containerd_version\x18\x01 \x01(\tR\x11containerdVersion\x12!\n" +
	"\frunc_version\x18\x02 \x01(\tR\vruncVersion\"\xc5\x01\n" +
	"\x19DownloadCRIBinariesStatus\x126\n" +
	"\x17containerd_download_url\x18\x01 \x01(\tR\x15containerdDownloadUrl\x12'\n" +
	"\x0fcontainerd_path\x18\x02 \x01(\tR\x0econtainerdPath\x12*\n" +
	"\x11runc_download_url\x18\x03 \x01(\tR\x0fruncDownloadUrl\x12\x1b\n" +
	"\trunc_path\x18\x04 \x01(\tR\bruncPathB5Z3go.goms.io/aks/AKSFlexNode/components/cri/v20260301b\beditionsp\xe9\a"

var file_components_cri_v20260301_action_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_components_cri_v20260301_action_proto_goTypes = []any{
	(*DownloadCRIBinaries)(nil),       // 0: aks.flex.components.cri.v20260301.DownloadCRIBinaries
	(*DownloadCRIBinariesSpec)(nil),   // 1: aks.flex.components.cri.v20260301.DownloadCRIBinariesSpec
	(*DownloadCRIBinariesStatus)(nil), // 2: aks.flex.components.cri.v20260301.DownloadCRIBinariesStatus
	(*api.Metadata)(nil),              // 3: aks.flex.components.api.Metadata
}
var file_components_cri_v20260301_action_proto_depIdxs = []int32{
	3, // 0: aks.flex.components.cri.v20260301.DownloadCRIBinaries.metadata:type_name -> aks.flex.components.api.Metadata
	1, // 1: aks.flex.components.cri.v20260301.DownloadCRIBinaries.spec:type_name -> aks.flex.components.cri.v20260301.DownloadCRIBinariesSpec
	2, // 2: aks.flex.components.cri.v20260301.DownloadCRIBinaries.status:type_name -> aks.flex.components.cri.v20260301.DownloadCRIBinariesStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_components_cri_v20260301_action_proto_init() }
func file_components_cri_v20260301_action_proto_init() {
	if File_components_cri_v20260301_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_components_cri_v20260301_action_proto_rawDesc), len(file_components_cri_v20260301_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_cri_v20260301_action_proto_goTypes,
		DependencyIndexes: file_components_cri_v20260301_action_proto_depIdxs,
		MessageInfos:      file_components_cri_v20260301_action_proto_msgTypes,
	}.Build()
	File_components_cri_v20260301_action_proto = out.File
	file_components_cri_v20260301_action_proto_goTypes = nil
	file_components_cri_v20260301_action_proto_depIdxs = nil
}
